services:
  remotion-render:
    image: 3n88/alpine-remotion-render:latest
    container_name: remotion-render
    restart: always
    user: "${PUID}:${PGID}"
    ports:
      - "3003:3003"
    devices:
      - /dev/dri:/dev/dri
    environment:
      - TZ=${TZ}
      - REMOTION_PORT=3003
    volumes:
      - ${DOCKER_HOME}/remotion-render:/config
